version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: Abc@123
      MYSQL_DATABASE: store_manager
      MYSQL_USER: admin
      MYSQL_PASSWORD: Abc@123
    ports:
      - "33061:3306"
    networks:
      - my-networks
  spring-app:
    build: .
    image: spring-app
    container_name: spring_app
    ports:
      - "8080:6789"
    environment:
      DB_HOST: mysql_container
      DB_PORT: 3306
      DB_USERNAME: admin
      DB_PASSWORD: Abc@123
    depends_on:
      - mysql
    networks:
      - my-networks
networks:
  my-networks:
    driver: bridge