server:
  port: 6789
spring:
  application:
    name: spring-secutiry-service
  #Datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/spring_secutiry}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:''}
    hikari:
      maximum-pool-size: 15
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DB_HIBERNATE_DDL_AUTO:none}
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.enable_lazy_load_no_trans: true
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext